Feature: Ingresar al módulo de Atención al cliente y soporte

  @HOG02
  Scenario: paga tu Factura
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    And   INGRESA AL BOTON MEDICION DE RED
    And   VERIFICA EL MENSAJE DE AUTORIZACION EN PANTALLA
    And   ACEPTA LA AUTORIZACION DE MEDICION
    And   REALIZA TEST DE VELOCIDAD
    Then  VERIFICA LA INFORMACION EN PANTALLA Y MANEJA CONDICIONALES
