Feature: Ingresar al módulo de entretenimiento

  ############################################### Hogar prioridad por barra entretenimiento

  @EN001
  Scenario: Ingresar a entretenimiento y validar Claro Video
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    And   SELECCIONA EL BOTON CLARO VIDEO
    And   VALIDA VERSION DE MINIPROGRAMA CLARO VIDEO
    Then  VALIDA REDIRECCION APP STORE CLARO VIDEO

  @EN0002
  Scenario: Ingresar a entretenimiento y validar redirección a Claro Club
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    And   SELECCIONA EL BOTON CLARO CLUB
    And   VALIDA VERSION DE MINIPROGRAMA CLARO CLUB
    Then  VALIDA REDIRECCION CLARO CLUB

  @EN003
  Scenario: Ingresar a entretenimiento y validar Claro Música
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    And   SELECCIONA EL BOTON CLARO MUSICA
    And   VALIDA VERSION DE MINIPROGRAMA CLARO MUSICA
    Then  VALIDA REDIRECCION CLARO MUSICA APP

  @EN004
  Scenario: Ingresar a entretenimiento y validar HBO max
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    And   SELECCIONA BOTON HBOMAX
    And   VALIDA VERSION DE MINIPROGRAMA HBO MAX
    Then  VALIDA REDIRECCION PAGINA A HBO MAX


  @EN005
  Scenario: Ingresar a entretenimiento y validar Disney+premium
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    And   SELECCIONA BOTON DISNEY PLUS
    And   VALIDAR VERSION DE MINIPROGRAMA DISNEY
    And   SELECCIONA PLAN PREMIUM DISNEY
    And   VALIDA TERMINOS Y CONDICIONES DISNEY PREMIUM
    Then  VALIDA REDIRECCIONAMIENTO ID ClARO

  @EN006
  Scenario: Ingresar a entretenimiento y validar Disney+ plan estándar
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   SELECCIONA BOTON DISNEY PLUS
    And   VALIDAR VERSION DE MINIPROGRAMA DISNEY
    And   SELECCIONA PLAN ESTANDAR DISNEY
    And   VALIDA TERMINOS Y CONDICIONES DISNEY ESTANDAR
    Then  VALIDA REDIRECCIONAMIENTO ID ClARO


  @EN007
  Scenario: Ingresar a entretenimiento y validar HotGo
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    And   SELECCIONA BOTON HOTGO
    And   VALIDAR VERSION DE MINIPROGRAMA HOTGO
    And   SELECCIONA PLAN HOTGO
    And   VALIDA TERMINOS Y CONDICIONES HOTGO
    Then  VALIDA REDIRECCIONAMIENTO ID ClARO


  @EN008
  Scenario: Ingresar a entretenimiento y validar Amazon Prime
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    And   SELECCIONA BOTON AMAZON PRIME
    And   VALIDAR VERSION DE MINIPROGRAMA AMAZONPRIME
    And   SELECCIONA PLAN AMAZON PRIME
    And   VALIDA TERMINOS Y CONDICIONES AMAZON PRIME
    Then  VALIDA REDIRECCIONAMIENTO ID ClARO


  @EN009
  Scenario: Ingresar a entretenimiento y validar Claro gaming cloud
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    And   SELECCIONA BOTON GAMING CLOUD
    And   VALIDAR VERSION DE MINIPROGRAMA GAMING CLOUD
    And   SELECCIONA PLAN GAMING CLOUD
    Then  VALIDA REDIRECCIONAMIENTO ID ClARO GAMING CLOUD

  @EN0010
  Scenario: Ingresar a entretenimiento y validar Claro win PlAY
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   SELECCIONA BOTON WIN PLAY
    And   VALIDAR VERSION DE MINIPROGRAMA WIN PLAY
    And   SELECCIONA PLAN WIN PLAY
    And   VALIDA TERMINOS Y CONDICIONES WIN PLAY
    Then  VALIDA REDIRECCIONAMIENTO ID ClARO



#  @SA063
#  Scenario: Ingresar a entretenimiento y validar Netflix con términos y condiciones
#    Given EL USUARIO ABRE LA SUPER APP
#    When  REALIZA EL INGRESO
#    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
#    And   SELECCIONA BOTON NETFLIX
#    And   VALIDA VERSION DE MINIPROGRAMA NETFLIX
#    And   VALIDA TERMINOS Y CONDICIONES NETFLIX
#    #Then  VALIDA REDIRECCIONAMIENTO ID ClARO
#
#
#  @SA066
#  Scenario: Ingresar a entretenimiento y validar Disney+ plan estándar
#    Given EL USUARIO ABRE LA SUPER APP
#    When  REALIZA EL INGRESO
#    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
#    And   SELECCIONA BOTON DISNEY PLUS
#    And   VALIDAR VERSION DE MINIPROGRAMA DISNEY
#    And   SELECCIONA PLAN ESTANDAR DISNEY
#    And   VALIDA TERMINOS Y CONDICIONES DISNEY ESTANDAR
#    Then  VALIDA REDIRECCIONAMIENTO ID ClARO
#
#  @SA067
#  Scenario: Ingresar a entretenimiento y validar Disney+ plan premium
#    Given EL USUARIO ABRE LA SUPER APP
#    When  REALIZA EL INGRESO
#    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
#    And   SELECCIONA BOTON DISNEY PLUS
#    And   VALIDAR VERSION DE MINIPROGRAMA DISNEY
#    And   SELECCIONA PLAN PREMIUM DISNEY
#    And   VALIDA TERMINOS Y CONDICIONES DISNEY PREMIUM
#    Then  VALIDA REDIRECCIONAMIENTO ID ClARO
#
#  @SA069
#  Scenario: Ingresar a entretenimiento y validar Amazon Prime con términos y condiciones
#    Given EL USUARIO ABRE LA SUPER APP
#    When  REALIZA EL INGRESO
#    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
#    And   SELECCIONA BOTON AMAZON PRIME
#    And   VALIDAR VERSION DE MINIPROGRAMA AMAZONPRIME
#    And   SELECCIONA PLAN AMAZON PRIME
#    And   VALIDA TERMINOS Y CONDICIONES AMAZON PRIME
#    Then  VALIDA REDIRECCIONAMIENTO ID ClARO
#
#
#
#
#
#  ############################################################## pospago prioridad por tus servicios favoritos
#
#  @SA082
#  Scenario: Validar redireccion Claro Video ingresando por tus servicios favoritos
#    Given EL USUARIO ABRE LA SUPER APP
#    When  REALIZA EL INGRESO
#    And   SELECCIONA EL BOTON VER MAS EN SECCION TUS SERVCICOS FAVORITOS
#    And   SELECCIONA EL BOTON CLARO VIDEO
#    And   VALIDA VERSION DE MINIPROGRAMA CLARO VIDEO
#    Then  VALIDA REDIRECCION APP STORE CLARO VIDEO
#
#  @SA083
#  Scenario: Validar redireccion Claro Musica ingresando por tus servicios favoritos
#    Given EL USUARIO ABRE LA SUPER APP
#    When  REALIZA EL INGRESO
#    And   SELECCIONA EL BOTON VER MAS EN SECCION TUS SERVCICOS FAVORITOS
#    And   SELECCIONA EL BOTON CLARO MUSICA
#    And   VALIDA VERSION DE MINIPROGRAMA CLARO MUSICA
#    Then  VALIDA REDIRECCION CLARO MUSICA APP
#
#
#  ############################################ Claro Club por explora y compra
#  @SA084
#  Scenario: Explora y Compra Redirección de Claro Club
#    Given EL USUARIO ABRE LA SUPER APP
#    When  REALIZA EL INGRESO
#    And   SELECCIONA EL BOTON CLARO CLUB EN EXPLORA Y COMPRA
#    And   VALIDA VERSION DE MINIPROGRAMA CLARO CLUB
#    Then  VALIDA REDIRECCION CLARO CLUB
#
#  ############################################ Entretenimiento Prepago prioridad
#  @PRE079
#  Scenario: Ingresar a entretenimiento y validar Claro Video Prepago
#    Given EL USUARIO ABRE LA SUPER APP
#    When  REALIZA EL INGRESO
#    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
#    And   SELECCIONA EL BOTON CLARO VIDEO
#    And   VALIDA VERSION DE MINIPROGRAMA PRE CLARO VIDEO
#    Then  VALIDA REDIRECCION APP STORE CLARO VIDEO
#
#  @PRE109
#  Scenario: Ingresar a entretenimiento y validar Claro Club Prepago
#    Given EL USUARIO ABRE LA SUPER APP
#    When  REALIZA EL INGRESO
#    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
#    And   SELECCIONA EL BOTON CLARO CLUB
#    And   VALIDA VERSION DE MINIPROGRAMA PRE CLARO CLUB
#    Then  VALIDA REDIRECCION CLARO CLUB
#
#  @PRE110
#  Scenario: Explora y Compra Redirección de Claro Club Prepago
#    Given EL USUARIO ABRE LA SUPER APP
#    When  REALIZA EL INGRESO
#    And   SELECCIONA EL BOTON CUPONES EN EXPLORA Y COMPRA
#    And   VALIDA VERSION DE MINIPROGRAMA PRE CLARO CLUB
#    Then  VALIDA REDIRECCION CLARO CLUB
#
#  @PRE082
#  Scenario: Ingresar a entretenimiento y validar Claro Música Prepago
#    Given EL USUARIO ABRE LA SUPER APP
#    When  REALIZA EL INGRESO
#    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
#    #And   VALIDA REDIRECCION A ENTRETENIMIENTO
#    And   SELECCIONA EL BOTON CLARO MUSICA
#    And   VALIDA VERSION DE MINIPROGRAMA PRE CLARO MUSICA
#    Then  VALIDA REDIRECCION CLARO MUSICA APP
#
#  @PRE112
#  Scenario: Validar redireccion Claro Video ingresando por tus servicios favoritos Prepago
#    Given EL USUARIO ABRE LA SUPER APP
#    When  REALIZA EL INGRESO
#    And   SELECCIONA EL BOTON VER MAS EN SECCION TUS SERVCICOS FAVORITOS
#    And   SELECCIONA EL BOTON CLARO VIDEO
#    And   VALIDA VERSION DE MINIPROGRAMA PRE CLARO VIDEO
#    Then  VALIDA REDIRECCION APP STORE CLARO VIDEO
#
##  @PRE111
##  Scenario: Validar redireccion Claro Musica ingresando por tus servicios favoritos Prepago
##    Given EL USUARIO ABRE LA SUPER APP
##    When  REALIZA EL INGRESO
##    And   SELECCIONA EL BOTON VER MAS EN SECCION TUS SERVCICOS FAVORITOS
##    And   SELECCIONA EL BOTON CLARO MUSICA
##    And   VALIDA VERSION DE MINIPROGRAMA PRE CLARO MUSICA
##    Then  VALIDA REDIRECCION CLARO MUSICA APP
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#  #******* NO ESTA DENTRO DEL CONTINUOS *************
#    @SA068
#  Scenario: Ingresar a entretenimiento y validar HotGo
#    Given EL USUARIO ABRE LA SUPER APP
#    When  REALIZA EL INGRESO
#    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
#    And   VALIDA REDIRECCION A ENTRETENIMIENTO
#    And   DESPLAZARSE HASTA EL MODULO TUS PLATAFORMAS FAVORITAS
#    And   SELECCIONA BOTON VER MAS PLATAFORMAS
#    And   SELECCIONA BOTON PlAY
#    Then  VALIDA REDIRECCION A PAGINA HOTGO
#
#  @SA065
#  Scenario: Ingresar a entretenimiento y validar HBOmax
#    Given EL USUARIO ABRE LA SUPER APP
#    When  REALIZA EL INGRESO
#    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
#    And   VALIDA REDIRECCION A ENTRETENIMIENTO
#    And   DESPLAZARSE HASTA EL MODULO TUS PLATAFORMAS FAVORITAS
#    And   SELECCIONA BOTON HBOMAX
#    Then  VALIDA REDIRECCION PAGINA A HBOMAX
#
#  @SA064
#  Scenario: Ingresar a entretenimiento y validar Win Play
#    Given EL USUARIO ABRE LA SUPER APP
#    When  REALIZA EL INGRESO
#    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
#    And   VALIDA REDIRECCION A ENTRETENIMIENTO
#    And   DESPLAZARSE HASTA EL MODULO TUS PLATAFORMAS FAVORITAS
#    And   SELECCIONA BOTON VER MAS PLATAFORMAS
#    And   SELECCIONA BOTON WIN PLAY
#    Then  VALIDA REDIRECCION A PAGINA WIN PLAY
#
#  @SA060
#  Scenario: Ingresar a entretenimiento y validar RED + TV en vivo
#    Given EL USUARIO ABRE LA SUPER APP
#    When  REALIZA EL INGRESO
#    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
#    And   VALIDA REDIRECCION A ENTRETENIMIENTO
#    And   SELECCIONA EL BOTON RED PLUS TV EN VIVO
#    Then  VALIDA REDIRECCION A RED PLUS TV EN VIVO
#
#  @SA061
#  Scenario: Ingresar a entretenimiento y validar RED + NOTICIAS
#    Given EL USUARIO ABRE LA SUPER APP
#    When  REALIZA EL INGRESO
#    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
#    And   VALIDA REDIRECCION A ENTRETENIMIENTO
#    And   DESPLAZARSE HASTA EL MODULO TUS PLATAFORMAS FAVORITAS
#    And   SELECCIONA BOTON VER MAS PLATAFORMAS
#    And   SELECCIONA BOTON RED PLUS NOTICIAS
#    And   SELECCIONA LA OPCION VER DETALLE CLARO MUSICA
#    Then  VALIDA REDIRECCION RED PLUS NOTICIAS
