# language: es

Característica: Ingresar al módulo de entretenimiento

  ############################################### Hogar prioridad por barra entretenimiento

  @EN001
  Escenario: Ingresar a entretenimiento y validar Claro Video
    Dado QUE EL USUARIO INGRESE A SUPER APP
    Cuando REALIZA EL INGRESO
    Y SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y SELECCIONA EL BOTON CLARO VIDEO
    Y VALIDA VERSION DE MINIPROGRAMA CLARO VIDEO
    Entonces VALIDA REDIRECCION APP STORE CLARO VIDEO

  @EN002
  Escenario: Ingresar a entretenimiento y validar redirección a Claro Club
    Dado QUE EL USUARIO INGRESE A SUPER APP
    Cuando REALIZA EL INGRESO
    Y SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y SELECCIONA EL BOTON CLARO CLUB
    Y VALIDA VERSION DE MINIPROGRAMA CLARO CLUB
    Entonces VALIDA REDIRECCION CLARO CLUB

  @EN003
  Escenario: Ingresar a entretenimiento y validar Claro Música
    Dado QUE EL USUARIO INGRESE A SUPER APP
    Cuando REALIZA EL INGRESO
    Y SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y SELECCIONA EL BOTON CLARO MUSICA
    Y VALIDA VERSION DE MINIPROGRAMA CLARO MUSICA
    Entonces VALIDA REDIRECCION CLARO MUSICA APP

  @EN004
  Escenario: Ingresar a entretenimiento y validar HBO max
    Dado QUE EL USUARIO INGRESE A SUPER APP
    Cuando REALIZA EL INGRESO
    Y SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y SELECCIONA BOTON HBOMAX
    Y VALIDA VERSION DE MINIPROGRAMA HBO MAX
    Entonces VALIDA REDIRECCION PAGINA A HBO MAX

  @EN005
  Escenario: Ingresar a entretenimiento y validar Disney+premium
    Dado QUE EL USUARIO INGRESE A SUPER APP
    Cuando REALIZA EL INGRESO
    Y SELECCIONA BOTON DISNEY PLUS
    Y VALIDAR VERSION DE MINIPROGRAMA DISNEY
    Y SELECCIONA PLAN PREMIUM DISNEY
    Y VALIDA TERMINOS Y CONDICIONES DISNEY PREMIUM
    Entonces VALIDA REDIRECCIONAMIENTO ID ClARO

  @EN006
  Escenario: Ingresar a entretenimiento y validar Disney+ plan estándar
    Dado QUE EL USUARIO INGRESE A SUPER APP
    Cuando REALIZA EL INGRESO
    Y SELECCIONA BOTON DISNEY PLUS
    Y VALIDAR VERSION DE MINIPROGRAMA DISNEY
    Y SELECCIONA PLAN ESTANDAR DISNEY
    Y VALIDA TERMINOS Y CONDICIONES DISNEY ESTANDAR
    Entonces VALIDA REDIRECCIONAMIENTO ID ClARO

  @EN007
  Escenario: Ingresar a entretenimiento y validar HotGo
    Dado QUE EL USUARIO INGRESE A SUPER APP
    Cuando REALIZA EL INGRESO
    Y SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y SELECCIONA BOTON HOTGO
    Y VALIDAR VERSION DE MINIPROGRAMA HOTGO
    Y SELECCIONA PLAN HOTGO
    Y VALIDA TERMINOS Y CONDICIONES HOTGO
    Entonces VALIDA REDIRECCIONAMIENTO ID ClARO

  @EN008
  Escenario: Ingresar a entretenimiento y validar Amazon Prime
    Dado QUE EL USUARIO INGRESE A SUPER APP
    Cuando REALIZA EL INGRESO
    Y SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y SELECCIONA BOTON AMAZON PRIME
    Y VALIDAR VERSION DE MINIPROGRAMA AMAZONPRIME
    Y SELECCIONA PLAN AMAZON PRIME
    Y VALIDA TERMINOS Y CONDICIONES AMAZON PRIME
    Entonces VALIDA REDIRECCIONAMIENTO ID ClARO

  @EN009
  Escenario: Ingresar a entretenimiento y validar Claro gaming cloud
    Dado QUE EL USUARIO INGRESE A SUPER APP
    Cuando REALIZA EL INGRESO
    Y SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y SELECCIONA BOTON GAMING CLOUD
    Y VALIDAR VERSION DE MINIPROGRAMA GAMING CLOUD
    Y SELECCIONA PLAN GAMING CLOUD
    Entonces VALIDA REDIRECCIONAMIENTO ID ClARO GAMING CLOUD

  @EN0010
  Escenario: Ingresar a entretenimiento y validar Claro win Play
    Dado QUE EL USUARIO INGRESE A SUPER APP
    Cuando REALIZA EL INGRESO
    Y SELECCIONA BOTON WIN PLAY
    Y VALIDAR VERSION DE MINIPROGRAMA WIN PLAY
    Y SELECCIONA PLAN WIN PLAY
    Y VALIDA TERMINOS Y CONDICIONES WIN PLAY
    Entonces VALIDA REDIRECCIONAMIENTO ID ClARO