# language: es

Característica: Gestión de servicios favoritos

  @SFPF001
  Escenario: Acceder a Paga tu factura desde Servicios Favoritos
    Dado QUE EL USUARIO INGRESE A SUPER APP
    Cuando REALIZA EL INGRESO
    Entonces VERIFICA VERSION DE LA SUPER APP
    Y INGRESA A TUS SERVICIOS FAVORITOS PAGA TU FACTURA

  @SFPF002
  Escenario: Descargar factura desde Paga tu factura
    Dado QUE EL USUARIO INGRESE A SUPER APP
    Cuando REALIZA EL INGRESO
    Entonces VERIFICA VERSION DE LA SUPER APP
    Y INGRESA A TUS SERVICIOS FAVORITOS PAGA TU FACTURA
    Y DESCARGAR FACTURA

  @SFPF003
  Escenario: Consultar pagos automáticos desde Paga tu factura
    Dado QUE EL USUARIO INGRESE A SUPER APP
    Cuando REALIZA EL INGRESO
    Entonces VERIFICA VERSION DE LA SUPER APP
    Y INGRESA A TUS SERVICIOS FAVORITOS PAGA TU FACTURA
    Y VALIDA PAGOS AUTOMATICOS

  @SFPF004
  Escenario: Enviar factura por correo electrónico
    Dado QUE EL USUARIO INGRESE A SUPER APP
    Cuando REALIZA EL INGRESO
    Entonces VERIFICA VERSION DE LA SUPER APP
    Y INGRESA A TUS SERVICIOS FAVORITOS PAGA TU FACTURA
    Y ENVIA FACTURA POR CORREO

  @SFPF005
  Escenario: Consultar detalle de la última facturación
    Dado QUE EL USUARIO INGRESE A SUPER APP
    Cuando REALIZA EL INGRESO
    Entonces VERIFICA VERSION DE LA SUPER APP
    Y INGRESA A TUS SERVICIOS FAVORITOS PAGA TU FACTURA
    Y VALIDA DETALLE ULTIMA FACTURACION

  @SFPF006
  Escenario: Consultar historial de pagos
    Dado QUE EL USUARIO INGRESE A SUPER APP
    Cuando REALIZA EL INGRESO
    Entonces VERIFICA VERSION DE LA SUPER APP
    Y INGRESA A TUS SERVICIOS FAVORITOS PAGA TU FACTURA
    Y VALIDA HISTORIAL DE PAGOS

  @SFNA001
  Escenario: Acceder a la opción Necesitas Ayuda Hogar
    Dado QUE EL USUARIO INGRESE A SUPER APP
    Cuando REALIZA EL INGRESO
    Entonces VERIFICA VERSION DE LA SUPER APP
    Y SELECCIONA LA OPCION NECESITAS AYUDA HOGAR