#
#Thu Apr 23 15:06:50 COT 2026
app=C\:\\Users\\CAPERAJU\\Auto_Mi_Claro_APP/src/test/resources/app/mi-claro.apk
appPackage=com.clarocolombia.miclaro
deviceScreenSize=1080x2372
orientation=PORTRAIT
autoDismissAlerts=true
deviceName=5617ee89
platform=LINUX
deviceUDID=5617ee89
appActivity=com.claro.superapp.SplashActivity
platformVersion=16
automationName=UiAutomator2
captureScreenshots=true
deviceModel=CPH2743
deviceManufacturer=OPPO
platformName=Android
